[tasks.uv-tool-all]
description = "Exedcute uv tool install"
run = """
#!/usr/bin/env fish

if command -v uv
    for tool in (bat "$XDG_CONFIG_HOME/uv/tools.txt")
        uv tool install (echo "$tool" | string split ' ')
    end
end
"""
